import 'package:fitness_app/core/widgets/widgets.dart';
import 'package:fitness_app/features/home/models/today_plan.dart';

/// Everything the prototype's stretch-info sheet (`stretchSheet()`) shows
/// beyond what [StretchPreview]/[ExploreStretch] already carry: how it
/// should feel, the steps to get into it, a common mistake, easier/harder
/// variations and when to be careful. Ported 1:1 from the prototype's
/// `STRETCHES` table.
class StretchGuide {
  const StretchGuide({
    required this.position,
    this.isEachSide = false,
    this.isDynamic = false,
    this.isKneeling = false,
    this.level = RoutineLevel.beginner,
    this.equipment = const [],
    required this.feel,
    required this.steps,
    required this.commonMistake,
    required this.easier,
    required this.harder,
    required this.cautions,
  });

  final StretchPosition position;
  final bool isEachSide;
  final bool isDynamic;
  final bool isKneeling;
  final RoutineLevel level;
  final List<String> equipment;

  /// Where the hold should be felt, e.g. "Along your sides, from hips to
  /// fingertips."
  final String feel;
  final List<String> steps;
  final String commonMistake;
  final String easier;
  final String harder;

  /// When to skip or modify the stretch, e.g. "Recent shoulder injury:
  /// keep arms below shoulder height."
  final String cautions;
}

/// Looks a [StretchGuide] up by [StretchPose] identity. Every stretch in
/// the app — today's plan, a routine's stretch list, the explore library —
/// references one of the canonical [StretchPoses] constants, so this never
/// needs a separate id or name key.
class StretchLibrary {
  const StretchLibrary._();

  static StretchGuide? guideFor(StretchPose pose) => _guides[pose];

  static final Map<StretchPose, StretchGuide> _guides = {
    StretchPoses.reach: const StretchGuide(
      position: StretchPosition.standing,
      feel: 'Along your sides, from hips to fingertips.',
      steps: [
        'Stand tall, feet hip-width apart.',
        'Interlace your fingers and press your palms up to the ceiling.',
        'Lengthen through your sides and breathe slowly.',
      ],
      commonMistake: 'Arching the lower back. Keep your ribs gently tucked.',
      easier: 'Reach one arm at a time.',
      harder: 'Rise onto your toes as you reach.',
      cautions: 'Recent shoulder injury: keep arms below shoulder height.',
    ),
    StretchPoses.sidebend: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Down the side of your waist and ribs.',
      steps: [
        'Stand tall and raise one arm overhead.',
        'Lean gently to the opposite side, hips square.',
        'Breathe into the stretched side.',
      ],
      commonMistake: 'Leaning forward or twisting instead of bending sideways.',
      easier: 'Keep the raised hand on your head.',
      harder: 'Hold a strap between both hands overhead.',
      cautions: 'Sharp back pain: make the bend smaller.',
    ),
    StretchPoses.necktilt: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Side of the neck, toward the top of the shoulder.',
      steps: [
        'Stand or sit tall with shoulders relaxed.',
        'Tilt your ear toward your shoulder.',
        'Rest the same-side hand lightly on your head. No pulling.',
      ],
      commonMistake:
          'Lifting the opposite shoulder, or pulling hard with the hand.',
      easier: 'Skip the hand and just tilt.',
      harder: 'Reach the opposite hand toward the floor.',
      cautions: 'Numbness or tingling in the arm: stop.',
    ),
    StretchPoses.cross: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Back of the shoulder.',
      steps: [
        'Bring one arm straight across your chest.',
        'Hook the other forearm just above the elbow.',
        'Draw the arm closer and keep the shoulder down.',
      ],
      commonMistake: 'Pressing on the elbow joint itself.',
      easier: 'Bend the stretching arm.',
      harder: 'Gently turn your head away from the arm.',
      cautions: 'Shoulder impingement: stay below the pinch.',
    ),
    StretchPoses.wallchest: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      equipment: ['Wall'],
      feel: 'Across the front of the chest and shoulder.',
      steps: [
        'Stand side-on to a wall.',
        'Place your palm on the wall at shoulder height, arm straight.',
        'Slowly turn your chest away from the wall.',
      ],
      commonMistake: 'Placing the hand too high, which pinches the shoulder.',
      easier: 'Bend the elbow to 90°.',
      harder: 'Slide the hand slightly higher.',
      cautions: 'History of dislocation: keep the hand low.',
    ),
    StretchPoses.fold: const StretchGuide(
      position: StretchPosition.standing,
      feel: 'Backs of your legs and lower back.',
      steps: [
        'Stand with feet hip-width apart, knees soft.',
        'Hinge at the hips and let your upper body hang.',
        'Let your head and arms be heavy.',
      ],
      commonMistake: 'Locking the knees and bouncing.',
      easier: 'Rest your hands on a chair or your thighs.',
      harder: 'Straighten your legs and hold opposite elbows.',
      cautions: 'Dizziness or high blood pressure: roll up slowly.',
    ),
    StretchPoses.quad: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Front of the thigh.',
      steps: [
        'Hold a wall or chair for balance.',
        'Bend one knee and hold the ankle behind you.',
        'Keep the knees together and tuck your tailbone.',
      ],
      commonMistake: 'Letting the knee drift out, or arching the back.',
      easier: 'Loop a strap or towel around the foot.',
      harder: 'Press the foot back into your hand.',
      cautions: 'Knee pain: use a strap and keep the bend partial.',
    ),
    StretchPoses.calf: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      equipment: ['Wall'],
      feel: 'Back of the lower leg.',
      steps: [
        'Place both hands on a wall.',
        'Step one foot back, heel down.',
        'Bend the front knee and lean in.',
      ],
      commonMistake: 'Letting the back heel lift.',
      easier: 'Shorten your stance.',
      harder: 'Bend the back knee slightly for the deeper calf.',
      cautions: 'Achilles injury: go gently.',
    ),
    StretchPoses.wrist: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Inside of the forearm.',
      steps: [
        'Extend one arm forward, palm up.',
        'With the other hand, draw the fingers gently down.',
        'Keep the elbow straight but not locked.',
      ],
      commonMistake: 'Yanking the fingers back.',
      easier: 'Bend the elbow slightly.',
      harder: 'Turn the palm to face forward.',
      cautions: 'Carpal tunnel: stop if tingling increases.',
    ),
    StretchPoses.chairtwist: const StretchGuide(
      position: StretchPosition.seated,
      isEachSide: true,
      equipment: ['Chair'],
      feel: 'Along the spine and the side of the ribs.',
      steps: [
        'Sit tall near the front of a chair.',
        'Turn your chest to one side and hold the backrest.',
        'Grow taller on each inhale, twist a little on each exhale.',
      ],
      commonMistake: 'Twisting from the neck only.',
      easier: 'Keep both hands on your thighs.',
      harder: 'Place the opposite elbow outside your knee.',
      cautions: 'Disc problems: keep the twist small.',
    ),
    StretchPoses.chairfig4: const StretchGuide(
      position: StretchPosition.seated,
      isEachSide: true,
      equipment: ['Chair'],
      feel: 'Outer hip and buttock.',
      steps: [
        'Sit tall and cross one ankle over the opposite knee.',
        'Keep the raised foot flexed.',
        'Hinge forward from the hips with a long back.',
      ],
      commonMistake: 'Rounding the back to go deeper.',
      easier: 'Rest the ankle on your shin instead.',
      harder: 'Press the raised knee gently down.',
      cautions: 'Knee pain: move the ankle lower on the leg.',
    ),
    StretchPoses.seatedfold: const StretchGuide(
      position: StretchPosition.seated,
      level: RoutineLevel.intermediate,
      feel: 'Backs of the legs.',
      steps: [
        'Sit with legs straight out in front.',
        'Hinge forward from the hips, reaching toward your feet.',
        'Keep the chest open rather than rounding down.',
      ],
      commonMistake: 'Collapsing the chest toward the knees.',
      easier: 'Bend your knees or sit on a folded towel.',
      harder: 'Loop a strap around your feet and walk your hands down.',
      cautions: 'Sciatica: bend the knees.',
    ),
    StretchPoses.butterfly: const StretchGuide(
      position: StretchPosition.seated,
      feel: 'Inner thighs and groin.',
      steps: [
        'Sit with the soles of your feet together.',
        'Let your knees fall out to the sides.',
        'Sit tall and hold your ankles.',
      ],
      commonMistake: 'Pushing the knees down with your hands.',
      easier: 'Move your feet further away from you.',
      harder: 'Hinge forward with a long spine.',
      cautions: 'Groin strain: keep your feet far away.',
    ),
    StretchPoses.seatedtwist: const StretchGuide(
      position: StretchPosition.seated,
      isEachSide: true,
      feel: 'Along the spine and outer hip.',
      steps: [
        'Sit cross-legged or with legs out.',
        'Place one hand behind you and the other on the opposite knee.',
        'Lengthen, then turn gently.',
      ],
      commonMistake: 'Leaning back onto the rear hand.',
      easier: 'Sit on a cushion.',
      harder: 'Cross one foot over the straight leg.',
      cautions: 'Pregnancy: twist away from the belly, gently.',
    ),
    StretchPoses.strap: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      equipment: ['Strap or towel'],
      feel: 'Back of the raised leg.',
      steps: [
        'Lie on your back and loop a strap around one foot.',
        'Raise the leg, keeping the other leg long.',
        'Hold the strap with both hands, shoulders relaxed.',
      ],
      commonMistake: 'Lifting the hips off the floor.',
      easier: 'Bend the lower knee, foot flat.',
      harder: 'Straighten the raised leg fully.',
      cautions: 'Later pregnancy: do it seated instead.',
    ),
    StretchPoses.kneehug: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      feel: 'Lower back and buttock.',
      steps: [
        'Lie on your back.',
        'Draw one knee toward your chest with both hands.',
        'Keep the other leg long or bent.',
      ],
      commonMistake: 'Lifting the head off the floor.',
      easier: 'Hold behind the thigh instead of the shin.',
      harder: 'Hug both knees at once.',
      cautions: 'Knee pain: hold behind the thigh.',
    ),
    StretchPoses.fig4: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      feel: 'Outer hip.',
      steps: [
        'Lie on your back, knees bent.',
        'Cross one ankle over the opposite knee.',
        'Draw the lower leg toward you.',
      ],
      commonMistake: 'Letting the head and shoulders lift.',
      easier: 'Keep the lower foot on the floor.',
      harder: 'Pull the lower thigh closer.',
      cautions: 'Hip replacement: check with your surgeon first.',
    ),
    StretchPoses.supinetwist: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      feel: 'Lower back and across the chest.',
      steps: [
        'Lie on your back and hug one knee in.',
        'Let it fall across your body.',
        'Open the arms wide and look the other way if comfortable.',
      ],
      commonMistake: 'Forcing the knee down to the floor.',
      easier: 'Put a cushion under the knee.',
      harder: 'Straighten the top leg.',
      cautions: 'Disc problems: keep the range small.',
    ),
    StretchPoses.child: const StretchGuide(
      position: StretchPosition.floor,
      isKneeling: true,
      feel: 'Lower back, hips and shoulders.',
      steps: [
        'Kneel and sit back toward your heels.',
        'Walk your hands forward and rest your forehead down.',
        'Breathe into your back.',
      ],
      commonMistake: 'Forcing the hips down to the heels.',
      easier: 'Place a cushion between calves and thighs.',
      harder: 'Walk the hands to one side for a side stretch.',
      cautions: 'Knee problems: try knee-to-chest instead.',
    ),
    StretchPoses.catcow: const StretchGuide(
      position: StretchPosition.floor,
      isKneeling: true,
      isDynamic: true,
      feel: 'Movement through the whole spine.',
      steps: [
        'Come to hands and knees.',
        'Inhale: drop the belly, lift the chest and gaze.',
        'Exhale: round the back, tuck chin and tailbone. Keep flowing.',
      ],
      commonMistake: 'Moving only from the neck.',
      easier: 'Do it seated on a chair.',
      harder: 'Slow each phase to a 5-count.',
      cautions: 'Wrist pain: rest on your fists or forearms.',
    ),
    StretchPoses.lunge: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      isKneeling: true,
      level: RoutineLevel.intermediate,
      feel: 'Front of the back hip.',
      steps: [
        'Kneel and step one foot forward.',
        'Shift your hips forward until you feel the front of the back hip.',
        'Lift the chest; arms up if comfortable.',
      ],
      commonMistake: 'Front knee drifting past the toes.',
      easier: 'Keep your hands on the front thigh.',
      harder: 'Reach back and hold the back foot.',
      cautions: 'Kneeling pain: pad the knee with a folded mat.',
    ),
    StretchPoses.cobra: const StretchGuide(
      position: StretchPosition.floor,
      level: RoutineLevel.intermediate,
      feel: 'Front of the body and along the lower back.',
      steps: [
        'Lie on your front, hands under your shoulders.',
        'Press gently to lift the chest.',
        'Keep elbows bent and shoulders away from your ears.',
      ],
      commonMistake: 'Pushing too high and pinching the lower back.',
      easier: 'Stay on your forearms (sphinx).',
      harder: 'Straighten the arms a little more.',
      cautions: 'Back pain when bending backward: skip this one.',
    ),
    StretchPoses.downdog: const StretchGuide(
      position: StretchPosition.floor,
      level: RoutineLevel.intermediate,
      feel: 'Backs of the legs and the shoulders.',
      steps: [
        'From hands and knees, lift your hips up and back.',
        'Press the floor away and lengthen your spine.',
        'Pedal the heels toward the floor.',
      ],
      commonMistake: 'Rounding the back to get the heels down.',
      easier: 'Keep the knees generously bent.',
      harder: 'Lift one leg at a time.',
      cautions: 'High blood pressure: keep it short.',
    ),
    StretchPoses.pigeon: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      level: RoutineLevel.advanced,
      feel: 'Deep in the outer hip of the front leg.',
      steps: [
        'From hands and knees, bring one knee forward behind the wrist.',
        'Slide the other leg straight back.',
        'Square the hips and lower down if comfortable.',
      ],
      commonMistake: 'Collapsing onto one hip.',
      easier: 'Place a cushion under the front hip.',
      harder: 'Fold forward onto your forearms.',
      cautions: 'Knee pain: use lying figure-4 instead.',
    ),
    StretchPoses.thread: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      isKneeling: true,
      feel: 'Between the shoulder blades.',
      steps: [
        'Start on hands and knees.',
        'Slide one arm under your body, palm up.',
        'Rest your shoulder and temple down.',
      ],
      commonMistake: 'Letting the hips shift sideways.',
      easier: 'Go only partway down.',
      harder: 'Reach the top arm overhead.',
      cautions: 'Neck discomfort: rest your head on a cushion.',
    ),
    StretchPoses.roller: const StretchGuide(
      position: StretchPosition.floor,
      equipment: ['Foam roller'],
      feel: 'Across the chest and upper back.',
      steps: [
        'Lie back with the roller under your upper back, across the spine.',
        'Support your head with your hands, or open your arms overhead.',
        'Breathe and let the upper back soften.',
      ],
      commonMistake: 'Arching the lower back.',
      easier: 'Keep your hands behind your head.',
      harder: 'Reach your arms overhead to the floor.',
      cautions: 'Osteoporosis: skip this one.',
    ),
    StretchPoses.bandpull: const StretchGuide(
      position: StretchPosition.standing,
      equipment: ['Resistance band'],
      isDynamic: true,
      feel: 'Front of the shoulders and chest.',
      steps: [
        'Hold a band in front of you, hands wide.',
        'Open your arms out to the sides, squeezing the shoulder blades.',
        'Return slowly and repeat.',
      ],
      commonMistake: 'Shrugging the shoulders up.',
      easier: 'Use a lighter band or a wider grip.',
      harder: 'Pause 3 seconds at full opening.',
      cautions: 'Shoulder pain: keep arms below shoulder height.',
    ),
    StretchPoses.bridge: const StretchGuide(
      position: StretchPosition.floor,
      equipment: ['Yoga block'],
      feel: 'Front of the hips.',
      steps: [
        'Lie on your back, knees bent, feet flat.',
        'Lift your hips and slide a block under your sacrum.',
        'Rest your weight on the block and relax.',
      ],
      commonMistake:
          'Placing the block under the lower back instead of the sacrum.',
      easier: 'Use the block on its lowest side.',
      harder: 'Straighten one leg along the floor.',
      cautions: 'Neck issues: keep your head still.',
    ),
    StretchPoses.halfsplit: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      isKneeling: true,
      level: RoutineLevel.advanced,
      feel: 'Back of the straight front leg.',
      steps: [
        'From a low lunge, shift your hips back over the back knee.',
        'Straighten the front leg, toes up.',
        'Hinge forward with a long spine.',
      ],
      commonMistake: 'Rounding the back to reach the toes.',
      easier: 'Use blocks under your hands.',
      harder: 'Fold your chest toward your thigh.',
      cautions: 'Hamstring strain: stay upright.',
    ),
    StretchPoses.torsotwist: const StretchGuide(
      position: StretchPosition.standing,
      isDynamic: true,
      feel: 'Warmth through the middle and upper back.',
      steps: [
        'Stand with feet wider than hips, knees soft.',
        'Let your arms swing loosely as you turn side to side.',
        'Let the heels pivot naturally.',
      ],
      commonMistake: 'Swinging too fast.',
      easier: 'Keep the movement small.',
      harder: 'Reach your arms longer as you turn.',
      cautions: 'Balance issues: stand near a wall.',
    ),
    StretchPoses.overheadtriceps: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Back of the upper arm and the side of your ribs.',
      steps: [
        'Raise one arm and bend the elbow so your hand reaches down between your shoulder blades.',
        'With the other hand, gently press the elbow back and down.',
        'Keep your ribs in and breathe slowly.',
      ],
      commonMistake: 'Arching the lower back or flaring the ribs.',
      easier: 'Press the elbow only lightly.',
      harder: 'Slide the hand lower down the spine.',
      cautions: 'Pain when lifting the arm overhead: skip this one. Never force the elbow.',
    ),
    StretchPoses.chestclasp: const StretchGuide(
      position: StretchPosition.standing,
      feel: 'Front of the chest and shoulders.',
      steps: [
        'Stand tall, feet hip-width apart.',
        'Clasp your hands behind your back and straighten your arms.',
        'Draw your shoulder blades together and lift your chest.',
      ],
      commonMistake: 'Flaring the ribs and over-arching the lower back.',
      easier: 'Hold a towel between your hands.',
      harder: 'Lift the clasped hands higher, away from your back.',
      cautions: 'Shoulder pain: keep the lift small.',
    ),
    StretchPoses.neckforward: const StretchGuide(
      position: StretchPosition.standing,
      feel: 'Back of the neck and the top of the upper back.',
      steps: [
        'Stand or sit tall with shoulders relaxed.',
        'Slowly lower your chin toward your chest.',
        'Let the weight of your head do the work and breathe slowly.',
      ],
      commonMistake: 'Rounding the whole upper back instead of just lowering the chin.',
      easier: 'Lower the chin only halfway.',
      harder: 'Rest your clasped hands lightly on the back of your head. No pulling.',
      cautions: 'Dizziness, or tingling in the arms: stop.',
    ),
    StretchPoses.chintuck: const StretchGuide(
      position: StretchPosition.standing,
      isDynamic: true,
      equipment: ['Wall'],
      feel: 'Back of the neck and the base of the skull.',
      steps: [
        'Stand with your back and head against a wall, looking straight ahead.',
        'Slide your chin straight back, as if making a double chin.',
        'Hold for 10 seconds, then relax and repeat.',
      ],
      commonMistake: 'Tilting the head down instead of sliding it straight back.',
      easier: 'Do it without the wall, with a smaller movement.',
      harder: 'Do it lying on your back with your head on the floor.',
      cautions: 'Dizziness or tingling in the arms: stop.',
    ),
    StretchPoses.standhamstring: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Back of the thigh of the front leg.',
      steps: [
        'Stand tall and place one heel forward on the floor, toes up.',
        'Bend the back knee slightly and hinge forward from the hips.',
        'Rest your hands on the front thigh and keep your back flat.',
      ],
      commonMistake: 'Rounding the back instead of hinging at the hips.',
      easier: 'Keep the front knee slightly bent.',
      harder: 'Straighten the front leg fully and fold a little deeper.',
      cautions: 'Pain behind the knee: ease off. Hold a wall for balance if needed.',
    ),
    StretchPoses.soleus: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      equipment: ['Wall'],
      feel: 'Lower calf, just above the heel.',
      steps: [
        'Stand facing a wall with your hands on it and one foot back.',
        'Bend both knees, keeping the back heel down.',
        'Shift your weight forward until you feel it low in the calf.',
      ],
      commonMistake: 'Letting the back heel lift.',
      easier: 'Shorten your stance.',
      harder: 'Step the back foot a little further away, heel still down.',
      cautions: 'Achilles injury: go gently.',
    ),
    StretchPoses.standfig4: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      level: RoutineLevel.intermediate,
      feel: 'Outer hip and buttock of the crossed leg.',
      steps: [
        'Stand tall near a wall for balance.',
        'Cross one ankle over the opposite thigh, just above the knee.',
        'Bend the standing knee and sit your hips back.',
      ],
      commonMistake: 'Rounding the back or letting the raised foot go slack.',
      easier: 'Keep a hand on the wall and bend only slightly.',
      harder: 'Sit deeper and lean the chest forward with a long spine.',
      cautions: 'Knee pain: keep the raised foot flexed. Balance issues: use the wall.',
    ),
    StretchPoses.walllat: const StretchGuide(
      position: StretchPosition.standing,
      equipment: ['Wall'],
      feel: 'Sides of the back, under the arms and shoulders.',
      steps: [
        'Face a wall and place your hands on it at shoulder height.',
        'Walk your feet back and hinge forward from the hips, arms straight.',
        'Press your chest toward the floor and hold.',
      ],
      commonMistake: 'Arching the lower back instead of pressing the chest down.',
      easier: 'Stand closer to the wall.',
      harder: 'Place your hands higher on the wall.',
      cautions: 'Pinching in the shoulders: ease off.',
    ),
    StretchPoses.highlunge: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      level: RoutineLevel.intermediate,
      feel: 'Front of the back hip and thigh.',
      steps: [
        'Step one foot back into a long lunge with the back heel lifted.',
        'Bend the front knee over the ankle.',
        'Reach both arms overhead and tuck your tailbone.',
      ],
      commonMistake: 'Front knee drifting past the toes, or arching the lower back.',
      easier: 'Keep your hands on your hips.',
      harder: 'Lower the hips a little deeper.',
      cautions: 'Knee pain: shorten the stance. Balance issues: stay near a wall.',
    ),
    StretchPoses.pyramid: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      level: RoutineLevel.intermediate,
      feel: 'Back of the front thigh and calf.',
      steps: [
        'Stand with one foot a short step ahead of the other, both feet flat.',
        'Hinge forward from the hips over the front leg with a long spine.',
        'Rest your hands on the floor or blocks and breathe.',
      ],
      commonMistake: 'Rounding the back to reach the floor.',
      easier: 'Bend the front knee slightly and place your hands on blocks.',
      harder: 'Fold deeper toward the front shin.',
      cautions: 'Hamstring strain: stay upright. Dizziness: roll up slowly.',
    ),
    StretchPoses.legswing: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      isDynamic: true,
      equipment: ['Wall'],
      feel: 'Front and back of the hip and thigh.',
      steps: [
        'Stand sideways to a wall and hold it for balance.',
        'Swing the outside leg forward and back in a smooth, controlled arc.',
        'Keep your torso upright and your standing knee soft.',
      ],
      commonMistake: 'Using momentum and arching the lower back.',
      easier: 'Make the swings smaller.',
      harder: 'Increase the range gradually as the hips loosen up.',
      cautions: 'Balance issues: hold the wall with both hands. Stop if the hip or groin pinches.',
    ),
    StretchPoses.hugstretch: const StretchGuide(
      position: StretchPosition.standing,
      feel: 'Between the shoulder blades and across the upper back.',
      steps: [
        'Stand tall with your feet hip-width apart.',
        'Wrap your arms around yourself as if giving a hug.',
        'Round your upper back, let your head drop forward and breathe.',
      ],
      commonMistake: 'Hunching the shoulders up to your ears.',
      easier: 'Hold your elbows instead.',
      harder: 'Switch which arm is on top halfway through.',
      cautions: 'Neck discomfort: keep the head upright.',
    ),
    StretchPoses.wristext: const StretchGuide(
      position: StretchPosition.standing,
      isEachSide: true,
      feel: 'Top of the forearm and wrist.',
      steps: [
        'Extend one arm forward, palm down.',
        'With the other hand, gently draw the back of the hand toward you.',
        'Keep the elbow straight but not locked.',
      ],
      commonMistake: 'Forcing the wrist past a comfortable range.',
      easier: 'Bend the elbow slightly.',
      harder: 'Hold a little longer with the elbow fully straight.',
      cautions: 'Tingling or sharp wrist pain: stop.',
    ),
    StretchPoses.squat: const StretchGuide(
      position: StretchPosition.standing,
      level: RoutineLevel.intermediate,
      feel: 'Hips, inner thighs and lower back.',
      steps: [
        'Stand with your feet a little wider than your shoulders, toes turned out.',
        'Lower your hips between your heels.',
        'Press your elbows gently inside your knees and keep your chest tall.',
      ],
      commonMistake: 'Letting the heels lift or the knees cave in.',
      easier: 'Hold a doorframe or place a rolled towel under your heels.',
      harder: 'Lower further and lengthen your spine.',
      cautions: 'Knee or ankle pain: reduce the depth.',
    ),
    StretchPoses.seatedsingle: const StretchGuide(
      position: StretchPosition.seated,
      isEachSide: true,
      feel: 'Back of the thigh of the straight leg.',
      steps: [
        'Sit with one leg straight and the other foot against your inner thigh.',
        'Flex the straight leg\'s foot and sit tall.',
        'Hinge forward from the hips over the straight leg.',
      ],
      commonMistake: 'Rounding the spine and pulling the head down.',
      easier: 'Sit on a folded towel.',
      harder: 'Hold the foot and fold further with a long spine.',
      cautions: 'Knee pain on the bent leg: support it with a cushion. Sciatica: bend the straight knee.',
    ),
    StretchPoses.chairfold: const StretchGuide(
      position: StretchPosition.seated,
      equipment: ['Chair'],
      feel: 'Lower back and the backs of the thighs.',
      steps: [
        'Sit near the front of a chair with your feet flat, slightly wider than your hips.',
        'Hinge forward from the hips and let your chest rest toward your thighs.',
        'Let your arms and head hang and breathe slowly.',
      ],
      commonMistake: 'Folding from the neck instead of the hips.',
      easier: 'Rest your hands on your thighs.',
      harder: 'Walk your hands down your shins toward the floor.',
      cautions: 'Dizziness: come up slowly. Back pain: fold only partway.',
    ),
    StretchPoses.chaircatcow: const StretchGuide(
      position: StretchPosition.seated,
      isDynamic: true,
      equipment: ['Chair'],
      feel: 'Along the whole spine.',
      steps: [
        'Sit tall with your hands on your knees.',
        'Inhale: arch your back and lift your chest.',
        'Exhale: round your back and tuck your chin. Keep flowing.',
      ],
      commonMistake: 'Moving only from the neck.',
      easier: 'Make the movements smaller.',
      harder: 'Slow each phase to a 5-count.',
      cautions: 'Back pain: keep the movement small.',
    ),
    StretchPoses.sphinx: const StretchGuide(
      position: StretchPosition.floor,
      feel: 'Lower back, abdomen and chest.',
      steps: [
        'Lie on your front with your legs extended.',
        'Place your forearms on the floor with your elbows under your shoulders.',
        'Press down gently to lift your chest and breathe.',
      ],
      commonMistake: 'Shrugging the shoulders up to your ears.',
      easier: 'Place your elbows slightly forward of your shoulders.',
      harder: 'Straighten the arms a little into a low cobra.',
      cautions: 'Back pain when bending backward: skip this one.',
    ),
    StretchPoses.happybaby: const StretchGuide(
      position: StretchPosition.floor,
      feel: 'Inner thighs, hips and lower back.',
      steps: [
        'Lie on your back and draw your knees toward your armpits.',
        'Hold the outsides of your feet or your shins.',
        'Keep your tailbone down and rock gently side to side.',
      ],
      commonMistake: 'Lifting the tailbone and head off the floor.',
      easier: 'Hold the backs of your thighs instead.',
      harder: 'Hold the feet and draw the knees closer to the floor beside your ribs.',
      cautions: 'Neck pain or late pregnancy: skip this one. Knee pain: hold behind the thighs.',
    ),
    StretchPoses.puppy: const StretchGuide(
      position: StretchPosition.floor,
      isKneeling: true,
      feel: 'Shoulders, upper back and spine.',
      steps: [
        'Start on hands and knees with your knees under your hips.',
        'Walk your hands forward while keeping your hips over your knees.',
        'Lower your chest and forehead toward the mat and breathe.',
      ],
      commonMistake: 'Letting the hips drift back toward the heels.',
      easier: 'Rest your forehead on a block or cushion.',
      harder: 'Walk your hands further forward and rest your chin on the mat.',
      cautions: 'Knee pain: pad your knees. Shoulder pinching: ease off.',
    ),
    StretchPoses.pronequad: const StretchGuide(
      position: StretchPosition.floor,
      isEachSide: true,
      feel: 'Front of the thigh and hip.',
      steps: [
        'Lie on your front and rest your forehead on your forearm.',
        'Bend one knee and hold the ankle with the same-side hand.',
        'Draw the heel gently toward your glute, keeping your hips down.',
      ],
      commonMistake: 'Lifting the hips or arching the lower back.',
      easier: 'Loop a strap or towel around the ankle.',
      harder: 'Gently press the foot into your hand.',
      cautions: 'Knee pain: use a strap and keep the bend partial. Stop if you feel cramping.',
    ),
    StretchPoses.camel: const StretchGuide(
      position: StretchPosition.floor,
      isKneeling: true,
      level: RoutineLevel.intermediate,
      feel: 'Front of the chest, thighs and hips.',
      steps: [
        'Kneel with your knees hip-width apart and thighs vertical.',
        'Place your hands on your lower back, or on your heels if comfortable.',
        'Lift your chest and arch back gently, keeping your hips over your knees.',
      ],
      commonMistake: 'Dropping the head back and crunching the lower back.',
      easier: 'Keep your hands on your lower back and tuck your toes under.',
      harder: 'Reach both hands to your heels.',
      cautions: 'Neck, back or blood-pressure issues: skip this one. Pad your knees.',
    ),
    StretchPoses.rockback: const StretchGuide(
      position: StretchPosition.floor,
      isKneeling: true,
      feel: 'Hips and lower back.',
      steps: [
        'Start on hands and knees with your spine long and neutral.',
        'Slowly rock your hips back toward your heels.',
        'Hold where you feel a stretch in the hips, then rock forward and repeat.',
      ],
      commonMistake: 'Rounding the lower back as the hips go back.',
      easier: 'Rock back only a short way.',
      harder: 'Widen your knees slightly and rock back further.',
      cautions: 'Knee pain: pad your knees or skip. Wrist pain: rest on your fists or forearms.',
    ),
    StretchPoses.supinereach: const StretchGuide(
      position: StretchPosition.floor,
      feel: 'Along the whole body, from the fingertips to the toes.',
      steps: [
        'Lie on your back with your legs straight.',
        'Reach your arms overhead along the floor.',
        'Point your toes and reach in opposite directions, breathing deeply.',
      ],
      commonMistake: 'Arching the lower back off the floor.',
      easier: 'Bend your knees with your feet flat.',
      harder: 'Interlace your fingers overhead and lean slightly to each side.',
      cautions: 'Overhead shoulder pain: keep your arms wider.',
    ),
    StretchPoses.tabletop: const StretchGuide(
      position: StretchPosition.floor,
      level: RoutineLevel.intermediate,
      feel: 'Front of the chest, shoulders and wrists.',
      steps: [
        'Sit with your knees bent and feet flat, hands on the floor behind you, fingers pointing toward your feet.',
        'Press into your hands and feet and lift your hips until your torso is level.',
        'Keep your neck long or let your head drop gently back.',
      ],
      commonMistake: 'Letting the hips sag or the shoulders shrug up.',
      easier: 'Keep your hips lower, closer to the floor.',
      harder: 'Extend one leg forward at a time.',
      cautions: 'Wrist or shoulder pain: skip this one. Neck pain: keep the head neutral.',
    ),
  };
}
